# Generated by Django 5.1.5 on 2025-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contributions_notes_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
