name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: |
          coverage run manage.py test
          coverage xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          organization: "learnathon-by-geeky-solutions"
          projectKey: "Learnathon-By-Geeky-Solutions_pipinstallc"
          args: -Dsonar.python.coverage.reportPaths=coverage.xml
