name: SonarCloud Token Debug

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug environment variables
        run: env

      - name: SonarCloud Scan (Minimal)
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_pipinstallc