name: SonarCloud Debugging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: pip install -r core/requirements.txt

      - name: Install coverage
        run: pip install coverage

      - name: Run tests and generate coverage report
        run: |
          coverage run core/manage.py test
          coverage xml
        env:
          DJANGO_SETTINGS_MODULE: core.settings

      - name: Debug environment variables
        run: env

      - name: List files in workspace
        run: ls -al

      - name: Show coverage file content
        run: cat coverage.xml || echo "coverage.xml not found"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization="lutions"
            -Dsonar.projectKey="Learnathons_pipinstallc"
            -Dsonar.python.coverage.reportPaths="coverage.xml"
